import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../domain/contract_model.dart';
import '../domain/product_info.dart';

class ContractPdfService {
  Future<pw.Document> generateContractPdf(ContractModel contract) async {
    final pdf = pw.Document();

    final fontRegular = await PdfGoogleFonts.robotoRegular();
    final fontBold = await PdfGoogleFonts.robotoBold();

    final dateFormatter = DateFormat('MMMM dd, yyyy');
    final currencyFormatter = NumberFormat.currency(
      symbol: '\$',
      decimalDigits: 2,
    );

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        theme: pw.ThemeData.withFont(base: fontRegular, bold: fontBold),
        header: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.center,
            children: [
              pw.Text(
                'SOCIALIST REPUBLIC OF VIETNAM',
                style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                'Independence - Freedom - Happiness',
                style: pw.TextStyle(
                  fontSize: 14,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 8),
              pw.Divider(),
              pw.SizedBox(height: 16),
            ],
          );
        },
        footer: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.center,
            children: [
              pw.Divider(),
              pw.SizedBox(height: 8),
              pw.Text(
                'Generated by Voltera System',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
              ),
              pw.Text(
                'Page ${context.pageNumber} of ${context.pagesCount}',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
              ),
            ],
          );
        },
        build: (context) {
          return [
            pw.Center(
              child: pw.Text(
                'ELECTRIC VEHICLE SALES CONTRACT',
                style: pw.TextStyle(
                  fontSize: 20,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),
            pw.SizedBox(height: 24),

            // Contract Info
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Contract ID: ${contract.id}'),
                pw.Text('Date: ${dateFormatter.format(contract.createdAt)}'),
              ],
            ),
            pw.SizedBox(height: 24),

            // Parties
            _buildSectionTitle('1. Parties'),
            pw.SizedBox(height: 8),
            pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Expanded(
                  child: _buildPartyInfo(
                    'Seller Information',
                    contract.seller.fullName,
                    contract.seller.email,
                  ),
                ),
                pw.SizedBox(width: 16),
                pw.Expanded(
                  child: _buildPartyInfo(
                    'Buyer Information',
                    contract.buyer.fullName,
                    contract.buyer.email,
                  ),
                ),
              ],
            ),
            pw.SizedBox(height: 24),

            // Product Info
            _buildSectionTitle('2. Product Information'),
            pw.SizedBox(height: 8),
            _buildProductInfo(contract.product),
            pw.SizedBox(height: 24),

            // Price
            _buildSectionTitle('3. Sale Price'),
            pw.SizedBox(height: 8),
            pw.Text(
              'The total sale price is agreed upon as: ${currencyFormatter.format(contract.salePrice)}',
              style: const pw.TextStyle(fontSize: 12),
            ),
            pw.SizedBox(height: 24),

            // Terms
            _buildSectionTitle('4. Terms and Conditions'),
            pw.SizedBox(height: 8),
            _buildParagraph(
              'Both parties agree to the terms and conditions outlined in this contract. The seller guarantees that the product is free from any liens or encumbrances and has the legal right to sell the product.',
            ),
            pw.SizedBox(height: 16),

            _buildSectionTitle('5. Rights and Obligations of Seller'),
            pw.SizedBox(height: 8),
            _buildParagraph(
              'The seller is obligated to hand over the product in the described condition along with all necessary documents. The seller must assist the buyer in the transfer of ownership if required.',
            ),
            pw.SizedBox(height: 16),

            _buildSectionTitle('6. Rights and Obligations of Buyer'),
            pw.SizedBox(height: 8),
            _buildParagraph(
              'The buyer is obligated to pay the agreed sale price in full. Upon taking possession, the buyer assumes all responsibility for the product.',
            ),
            pw.SizedBox(height: 16),

            _buildSectionTitle('7. Contract Effectiveness'),
            pw.SizedBox(height: 8),
            _buildParagraph(
              'This contract becomes effective immediately upon signing by both parties.',
            ),
            pw.SizedBox(height: 48),

            // Signatures
            _buildSectionTitle('Signature Section'),
            pw.SizedBox(height: 16),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
              children: [
                _buildSignatureBlock('Seller', contract.signedBySeller),
                _buildSignatureBlock('Buyer', contract.signedByBuyer),
              ],
            ),
          ];
        },
      ),
    );

    return pdf;
  }

  pw.Widget _buildSectionTitle(String title) {
    return pw.Text(
      title,
      style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
    );
  }

  pw.Widget _buildPartyInfo(String title, String name, String email) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(8),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            title,
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 12),
          ),
          pw.SizedBox(height: 8),
          pw.Text('Full Name: $name', style: const pw.TextStyle(fontSize: 12)),
          pw.SizedBox(height: 4),
          pw.Text('Email: $email', style: const pw.TextStyle(fontSize: 12)),
        ],
      ),
    );
  }

  pw.Widget _buildProductInfo(ProductInfo product) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(8),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
      ),
      child: product.map(
        vehicle: (v) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            _buildInfoRow('Type:', 'Vehicle'),
            _buildInfoRow('Name:', v.name),
            _buildInfoRow(
              'Brand/Model:',
              '${v.brand} ${v.model} (${v.version})',
            ),
            _buildInfoRow('Year:', '${v.yearManufacture}'),
            _buildInfoRow('Battery Capacity:', '${v.batteryCapacity} kWh'),
            _buildInfoRow('ODO:', '${v.odo} km'),
            _buildInfoRow('Color:', v.color),
          ],
        ),
        battery: (b) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            _buildInfoRow('Type:', 'Battery'),
            _buildInfoRow('Name:', b.name),
            _buildInfoRow('Serial Number:', b.serialNumber),
            _buildInfoRow(
              'Capacity:',
              '${b.remainingCapacity} / ${b.originalCapacity} kWh',
            ),
            _buildInfoRow('Voltage:', '${b.voltage} V'),
            _buildInfoRow('Cycle Count:', '${b.cycleCount}'),
            _buildInfoRow('Warranty:', b.warranty),
            _buildInfoRow('Mileage Covered:', '${b.mileageCovered} km'),
          ],
        ),
      ),
    );
  }

  pw.Widget _buildInfoRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 4),
      child: pw.Row(
        children: [
          pw.SizedBox(
            width: 120,
            child: pw.Text(
              label,
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 12),
            ),
          ),
          pw.Expanded(
            child: pw.Text(value, style: const pw.TextStyle(fontSize: 12)),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildParagraph(String text) {
    return pw.Text(
      text,
      style: const pw.TextStyle(fontSize: 12, lineSpacing: 1.5),
      textAlign: pw.TextAlign.justify,
    );
  }

  pw.Widget _buildSignatureBlock(String role, bool isSigned) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        pw.Text(
          '$role Signature',
          style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 14),
        ),
        pw.SizedBox(height: 16),
        pw.Container(
          width: 150,
          height: 60,
          alignment: pw.Alignment.center,
          decoration: pw.BoxDecoration(
            border: pw.Border.all(
              color: isSigned ? PdfColors.green : PdfColors.red,
            ),
            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
          ),
          child: pw.Text(
            isSigned ? 'SIGNED' : 'NOT SIGNED',
            style: pw.TextStyle(
              color: isSigned ? PdfColors.green : PdfColors.red,
              fontWeight: pw.FontWeight.bold,
              fontSize: 16,
            ),
          ),
        ),
      ],
    );
  }
}
