// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-fu24iYr0Bg611rNzHZHOLgD5Cyj6za4',
    appId: '1:1020624026276:web:06bcb06837741949020431',
    messagingSenderId: '1020624026276',
    projectId: 'voltera-d4928',
    authDomain: 'voltera-d4928.firebaseapp.com',
    storageBucket: 'voltera-d4928.firebasestorage.app',
    measurementId: 'G-EHZHXMDKG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBueOojaFmNhX5uGbGjKvvmtKpfj2eaMVk',
    appId: '1:1020624026276:android:cf7780ee4c71e232020431',
    messagingSenderId: '1020624026276',
    projectId: 'voltera-d4928',
    storageBucket: 'voltera-d4928.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3B41RnFqMGOLleNK9cRaLMLcoskdgE40',
    appId: '1:1020624026276:ios:62377a5ffb4e1197020431',
    messagingSenderId: '1020624026276',
    projectId: 'voltera-d4928',
    storageBucket: 'voltera-d4928.firebasestorage.app',
    iosBundleId: 'com.example.voltera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3B41RnFqMGOLleNK9cRaLMLcoskdgE40',
    appId: '1:1020624026276:ios:62377a5ffb4e1197020431',
    messagingSenderId: '1020624026276',
    projectId: 'voltera-d4928',
    storageBucket: 'voltera-d4928.firebasestorage.app',
    iosBundleId: 'com.example.voltera',
  );
}
